### ISSUE TITLE
is there any caching solution out there implemented with cats-stm ?

### ISSUE THREAD

**Issue by okouyad** [TimWSpence/cats-stm#325]
I'm looking for a ready made purely functional caching solution, and wonder if something based on cats-stm exist out there ?

**Comment by TimWSpence** [comment]
Hi @okouyad, sorry I just saw this issue. Good question!  I'm not aware of any.

What were you thinking it would look like? My guess is using stm to ensure that we only fetch/construct a value once if isn't in the cache?

**Comment by TimWSpence** [comment]
@okouyad are you happy for me to close this issue?

**Comment by Maatary** [comment]
My very bad for the late reply. I have just be overwhelm with pressing matter at work. Also in the mean i got some info on this. That this would not be a performant solution generally speaking.

**Comment by TimWSpence** [comment]
> My very bad for the late reply. I have just be overwhelm with pressing matter at work. Also in the mean i got some info on this. That this would not be a performant solution generally speaking.

No worries! :)
